# Generated by Django 3.1.3 on 2020-11-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text='Required: First Name. 200 characters or less.', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text='Required: Last Name. 200 characters or less.', max_length=200),
        ),
    ]
