# Generated by Django 3.1.3 on 2020-11-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201112_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='biography',
            field=models.TextField(help_text='Tell us about yourself.', null=True),
        ),
    ]
