# Generated by Django 3.1.3 on 2020-11-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug_title',
            field=models.SlugField(default=models.CharField(help_text='Enter a Title (Max 200 characters)', max_length=200), editable=False),
        ),
    ]
