# Generated by Django 3.1.3 on 2020-11-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_slug_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug_title',
        ),
    ]
